name: unit test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: Ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.sha}}

      - name: install node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: install dependencies
        run: npm ci

      - name: Run test
        run: npm test
        env:
          SPLITWISE_GROUP_ID: ${{ secrets.SPLITWISE_GROUP_ID }}
          USER1_ID: ${{ secrets.USER1_ID }}
          USER2_ID: ${{ secrets.USER2_ID }}
          USER1_RATE: ${{ secrets.USER1_ID }}
          USER2_RATE: ${{ secrets.USER2_ID }}
